DEBUG 2023-05-23 16:18:16.519 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-05-23 16:18:16.520 UTC: 	 Running on: Linux lxplus701.cern.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-05-23 16:18:16.520 UTC: 	 Executing command: 'status'
DEBUG 2023-05-23 16:18:16.520 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adattamu/.crab3
ERROR 2023-05-23 16:18:16.521 UTC: 	 Error: CumulantMB/crab_PbPb2018_PbPb_cumulants_std_MiniAOD is not a valid CRAB project directory.
ERROR 2023-05-23 16:18:16.521 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: CumulantMB/crab_PbPb2018_PbPb_cumulants_std_MiniAOD is not a valid CRAB project directory.
INFO 2023-05-23 16:18:16.545 UTC: 	 Log file is /eos/home-a/adattamu/Analysis_CMSSW/pbpb_miniaod/CMSSW_11_2_2/src/Analyzers/Cumulants/python/crab.log
DEBUG 2023-05-23 16:18:42.341 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-05-23 16:18:42.341 UTC: 	 Running on: Linux lxplus701.cern.ch 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-05-23 16:18:42.341 UTC: 	 Executing command: 'status'
DEBUG 2023-05-23 16:18:42.341 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adattamu/.crab3
ERROR 2023-05-23 16:18:42.342 UTC: 	 Error: CumulantMB/crab_PbPb2018_PbPb_cumulants_std_MiniAOD is not a valid CRAB project directory.
ERROR 2023-05-23 16:18:42.342 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: CumulantMB/crab_PbPb2018_PbPb_cumulants_std_MiniAOD is not a valid CRAB project directory.
INFO 2023-05-23 16:18:42.356 UTC: 	 Log file is /eos/home-a/adattamu/Analysis_CMSSW/pbpb_miniaod/CMSSW_11_2_2/src/Analyzers/Cumulants/python/crab.log
DEBUG 2023-05-30 10:24:51.461 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-05-30 10:24:51.461 UTC: 	 Running on: Linux lxplus717.cern.ch 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-05-30 10:24:51.461 UTC: 	 Executing command: 'status'
DEBUG 2023-05-30 10:24:51.461 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adattamu/.crab3
ERROR 2023-05-30 10:24:51.463 UTC: 	 Error: CumulantMB/crab_PbPb2018_PbPb_cumulants_dataset3_2sub_MiniAOD is not a valid CRAB project directory.
ERROR 2023-05-30 10:24:51.463 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: CumulantMB/crab_PbPb2018_PbPb_cumulants_dataset3_2sub_MiniAOD is not a valid CRAB project directory.
INFO 2023-05-30 10:24:51.469 UTC: 	 Log file is /eos/home-a/adattamu/Analysis_CMSSW/pbpb_miniaod/CMSSW_11_2_2/src/Analyzers/Cumulants/python/crab.log
DEBUG 2023-06-09 19:30:31.310 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-06-09 19:30:31.310 UTC: 	 Running on: Linux lxplus7106.cern.ch 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-06-09 19:30:31.310 UTC: 	 Executing command: 'kill'
DEBUG 2023-06-09 19:30:31.311 UTC: 	 Found CRAB cache file /afs/cern.ch/user/a/adattamu/.crab3
ERROR 2023-06-09 19:30:31.312 UTC: 	 Error: CumulantMB/crab_PbPb2018_no_eff_corr is not a valid CRAB project directory.
ERROR 2023-06-09 19:30:31.313 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: CumulantMB/crab_PbPb2018_no_eff_corr is not a valid CRAB project directory.
INFO 2023-06-09 19:30:31.316 UTC: 	 Log file is /eos/home-a/adattamu/Analysis_CMSSW/pbpb_miniaod/CMSSW_11_2_2/src/Analyzers/Cumulants/python/crab.log
